server:
  maxThreads: 8
  requestLog:
    appenders: []

logging:
  level: INFO
  appenders: # []
    - type: console
      logFormat: "%-5p [%d{ISO8601,UTC}] %c: %m [%t]%n%rEx %X"

# Zipkin-specific options.
zipkin:
  enabled: true
  collector: http
  baseUrl: http://127.0.0.1:9411/
  serviceHost: 127.0.0.1
  servicePort: 8080
  connectTimeout: 10s
  readTimeout: 60s

zipkinClient:
  serviceName: hello-world-client
  timeout: 2s